# Generated by Django 5.2.7 on 2026-01-10 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_blog', 'Может управлять блогом')], 'verbose_name': 'Блоговая запись', 'verbose_name_plural': 'Блоговые записи'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='BlogModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('needs_work', 'Требует доработки')], default='pending', max_length=20, verbose_name='Статус модерации')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('moderated_at', models.DateTimeField(auto_now=True, verbose_name='Дата модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='blog.blogpost', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Модерация статьи',
                'verbose_name_plural': 'Модерации статей',
                'ordering': ['-moderated_at'],
            },
        ),
    ]
